### ISSUE TITLE
Prepare for GNOME Shell 45 extension ESM port

### ISSUE THREAD

**Issue by zhiiwg** [egormanga/gnome-extension-huawei-wmi#10]
> [GNOME Shell 45 port guide](https://gjs.guide/extensions/upgrading/gnome-shell-45.html) is out. Since GNOME Shell 45 moved to ESM, we want all developers to port their extensions before 45.0 release (September 20th) so they can report to us about the elements needed to be exported (in case they are not exported already).
> 
> We also offer our help to all developers on [GNOME Discourse](https://discourse.gnome.org/) and GNOME Extensions Matrix channel: [GNOME Matrix Channel](https://matrix.to/#/#extensions:gnome.org) IRC Bridge: irc://irc.gimpnet.org/shell-extensions

Since GNOME 45 is to be released on September, so we should consider an ESM port for compatibility.

Thanks for your work!

**Comment by Sblash** [comment]
@egormanga thanks a lot!
