### ISSUE TITLE
V3 extension does not start!

### ISSUE THREAD

**Issue by cihatertem** [egormanga/gnome-extension-huawei-wmi#2]
Here is the error:
"Gio.IOErrorEnum: Error opening file /sys/devices/platform/huawei-wmi/power_unlock: No such file or directory"
I am on Huawei matebook 14s with uptodate Archlinux.

**Comment by egormanga** [comment]
Okay, there is a requirement now for the new kernel driver version, which has not been merged yet. For now, it's overall better to use and test the [PR](https://github.com/aymanbagabas/Huawei-WMI/pull/57) version, but in later revisions I will fix that.

**Comment by egormanga** [comment]
Upd. I've been told that power_unlock feature is already on the [feat/kbdlight](https://github.com/aymanbagabas/Huawei-WMI/tree/feat/kbdlight) branch at this point.

**Comment by egormanga** [comment]
Fixed by c01e8929f91fe866089777fe00aa5904f129979c.

**Comment by cihatertem** [comment]
Thanks for your effort! I have just updated the extension and works perfect except Power unlock and I understand the kernel support hasn't been merged yet.
Btw what is power unlock option? :)

**Comment by egormanga** [comment]
Power Unlock is the same feature as activated via `Fn+P` in Windows (with pre-installed PC Manager software). We don't really know yet what it actually does, but it seems to lift the CPU power limit (TDP) a bit.

Upd. See: https://github.com/aymanbagabas/Huawei-WMI/pull/56#issuecomment-1066114478
